export const tierOptions = [
    { value: "starter", label: "Starter", color: "bg-green-500" },
    { value: "bronze", label: "Bronze", color: "bg-amber-600" },
    { value: "silver", label: "Silver", color: "bg-gray-400" },
    { value: "gold", label: "Gold", color: "bg-yellow-500" },
    { value: "platinum", label: "Platinum", color: "bg-slate-300" },
    { value: "diamond", label: "Diamond", color: "bg-cyan-400" },
];

export const aiIcons = [
    { name: "ChatGPT", emoji: "💬" },
    { name: "GPT-4", emoji: "🧠" },
    { name: "Claude", emoji: "🤖" },
    { name: "Gemini", emoji: "♊" },
    { name: "Llama", emoji: "🦙" },
    { name: "Mistral", emoji: "🌪️" },
    { name: "Bard", emoji: "🎭" },
    { name: "Copilot", emoji: "✈️" },
    { name: "DeepSeek", emoji: "🔍" },
    { name: "Perplexity", emoji: "🎯" },
    { name: "Stable Diffusion", emoji: "🎨" },
    { name: "DALL-E", emoji: "🖼️" },
    { name: "Midjourney", emoji: "🌌" },
    { name: "Anthropic", emoji: "🔬" },
    { name: "OpenAI", emoji: "⚡" },
    { name: "Meta AI", emoji: "🔷" },
    { name: "Google AI", emoji: "🔴" },
    { name: "Cohere", emoji: "🌐" },
    { name: "Hugging Face", emoji: "🤗" },
    { name: "Replicate", emoji: "🔄" },
    { name: "Runway", emoji: "🎬" },
    { name: "Character AI", emoji: "👤" },
    { name: "Jasper", emoji: "✍️" },
    { name: "You.com", emoji: "🔎" },
];